name: Deploy Hugo site to GitHub Pages (Stable - Peaceiris Core)

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source (with submodules)
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.147.0'
        extended: true

    - name: Build
      run: hugo --minify

    - name: List current directory
      run: ls -al
    
    - name: List public directory
      run: ls -al public || echo "public directory not found"

    - name: Deploy to gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ github.workspace }}/public
